import type { Source } from '@/lib/types';

/**
 * The source registry.
 *
 * Rules (docs/03-source-map.md):
 *  - Tier 1 (RFCs, papers, official docs) and tier 2 (textbooks, courses) establish fact.
 *  - Tier 3 (engineering blogs) establishes what one company did, at one time.
 *  - Tier 4 (interview-prep) establishes interview convention only. Never technical fact.
 *
 * `authoritativeFor` exists to stop lazy citation: if a claim is not in that list,
 * this is the wrong source for it.
 */
export const SOURCES: Source[] = [
  /* ------------------------------------------------------ tier 1: standards */
  {
    id: 'rfc9110',
    title: 'RFC 9110: HTTP Semantics',
    url: 'https://www.rfc-editor.org/rfc/rfc9110',
    tier: 1,
    kind: 'rfc',
    year: 2022,
    authoritativeFor: ['HTTP methods', 'status codes', 'idempotency of methods', 'headers'],
  },
  {
    id: 'rfc9111',
    title: 'RFC 9111: HTTP Caching',
    url: 'https://www.rfc-editor.org/rfc/rfc9111',
    tier: 1,
    kind: 'rfc',
    year: 2022,
    authoritativeFor: ['cache-control directives', 'freshness', 'validation', 'stale responses'],
  },
  {
    id: 'rfc9112',
    title: 'RFC 9112: HTTP/1.1',
    url: 'https://www.rfc-editor.org/rfc/rfc9112',
    tier: 1,
    kind: 'rfc',
    year: 2022,
    authoritativeFor: ['HTTP/1.1 message framing', 'persistent connections', 'chunked transfer'],
  },
  {
    id: 'rfc9113',
    title: 'RFC 9113: HTTP/2',
    url: 'https://www.rfc-editor.org/rfc/rfc9113',
    tier: 1,
    kind: 'rfc',
    year: 2022,
    authoritativeFor: ['multiplexing', 'streams', 'HPACK header compression', 'flow control'],
  },
  {
    id: 'rfc9114',
    title: 'RFC 9114: HTTP/3',
    url: 'https://www.rfc-editor.org/rfc/rfc9114',
    tier: 1,
    kind: 'rfc',
    year: 2022,
    authoritativeFor: ['HTTP over QUIC', 'stream independence'],
  },
  {
    id: 'rfc9000',
    title: 'RFC 9000: QUIC, a UDP-Based Multiplexed and Secure Transport',
    url: 'https://www.rfc-editor.org/rfc/rfc9000',
    tier: 1,
    kind: 'rfc',
    year: 2021,
    authoritativeFor: ['QUIC handshake', 'connection migration', 'head-of-line blocking'],
  },
  {
    id: 'rfc9293',
    title: 'RFC 9293: Transmission Control Protocol (TCP)',
    url: 'https://www.rfc-editor.org/rfc/rfc9293',
    tier: 1,
    kind: 'rfc',
    year: 2022,
    authoritativeFor: ['TCP handshake', 'reliable delivery', 'flow control', 'connection states'],
  },
  {
    id: 'rfc8446',
    title: 'RFC 8446: The Transport Layer Security (TLS) Protocol Version 1.3',
    url: 'https://www.rfc-editor.org/rfc/rfc8446',
    tier: 1,
    kind: 'rfc',
    year: 2018,
    authoritativeFor: ['TLS 1.3 handshake', '1-RTT and 0-RTT', 'replay risk of 0-RTT'],
  },
  {
    id: 'rfc1035',
    title: 'RFC 1035: Domain Names - Implementation and Specification',
    url: 'https://www.rfc-editor.org/rfc/rfc1035',
    tier: 1,
    kind: 'rfc',
    year: 1987,
    authoritativeFor: ['DNS record types', 'TTL semantics', 'resolver behaviour'],
  },
  {
    id: 'rfc6749',
    title: 'RFC 6749: The OAuth 2.0 Authorization Framework',
    url: 'https://www.rfc-editor.org/rfc/rfc6749',
    tier: 1,
    kind: 'rfc',
    year: 2012,
    authoritativeFor: ['OAuth grant types', 'tokens', 'authorization vs authentication'],
  },
  {
    id: 'rfc7519',
    title: 'RFC 7519: JSON Web Token (JWT)',
    url: 'https://www.rfc-editor.org/rfc/rfc7519',
    tier: 1,
    kind: 'rfc',
    year: 2015,
    authoritativeFor: ['JWT structure', 'claims', 'signature verification'],
  },
  {
    id: 'rfc6455',
    title: 'RFC 6455: The WebSocket Protocol',
    url: 'https://www.rfc-editor.org/rfc/rfc6455',
    tier: 1,
    kind: 'rfc',
    year: 2011,
    authoritativeFor: ['WebSocket upgrade', 'framing', 'persistent bidirectional connections'],
  },

  /* ------------------------------------------------------ tier 1: papers */
  {
    id: 'dynamo',
    title: "Dynamo: Amazon's Highly Available Key-value Store",
    author: 'DeCandia et al.',
    url: 'https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf',
    tier: 1,
    kind: 'paper',
    year: 2007,
    authoritativeFor: [
      'consistent hashing with virtual nodes',
      'sloppy quorum',
      'hinted handoff',
      'vector clocks',
      'availability over consistency',
    ],
  },
  {
    id: 'spanner',
    title: "Spanner: Google's Globally-Distributed Database",
    author: 'Corbett et al.',
    url: 'https://research.google/pubs/pub39966/',
    tier: 1,
    kind: 'paper',
    year: 2012,
    authoritativeFor: [
      'TrueTime',
      'externally consistent transactions',
      'commit wait',
      'global distribution with strong consistency',
    ],
  },
  {
    id: 'bigtable',
    title: 'Bigtable: A Distributed Storage System for Structured Data',
    author: 'Chang et al.',
    url: 'https://research.google/pubs/pub27898/',
    tier: 1,
    kind: 'paper',
    year: 2006,
    authoritativeFor: ['wide-column model', 'tablets', 'SSTables', 'range partitioning'],
  },
  {
    id: 'gfs',
    title: 'The Google File System',
    author: 'Ghemawat, Gobioff, Leung',
    url: 'https://research.google/pubs/pub51/',
    tier: 1,
    kind: 'paper',
    year: 2003,
    authoritativeFor: ['large-object storage', 'chunk replication', 'single-master metadata'],
  },
  {
    id: 'mapreduce',
    title: 'MapReduce: Simplified Data Processing on Large Clusters',
    author: 'Dean, Ghemawat',
    url: 'https://research.google/pubs/pub62/',
    tier: 1,
    kind: 'paper',
    year: 2004,
    authoritativeFor: ['batch data-parallel processing', 'stragglers', 'speculative execution'],
  },
  {
    id: 'raft',
    title: 'In Search of an Understandable Consensus Algorithm (Raft)',
    author: 'Ongaro, Ousterhout',
    url: 'https://raft.github.io/raft.pdf',
    tier: 1,
    kind: 'paper',
    year: 2014,
    authoritativeFor: [
      'leader election',
      'terms',
      'log replication',
      'commit rules',
      'membership changes',
      'consensus safety and liveness',
    ],
  },
  {
    id: 'paxos-simple',
    title: 'Paxos Made Simple',
    author: 'Leslie Lamport',
    url: 'https://lamport.azurewebsites.net/pubs/paxos-simple.pdf',
    tier: 1,
    kind: 'paper',
    year: 2001,
    authoritativeFor: ['consensus safety', 'proposal numbers', 'majority intersection'],
  },
  {
    id: 'lamport-clocks',
    title: 'Time, Clocks, and the Ordering of Events in a Distributed System',
    author: 'Leslie Lamport',
    url: 'https://lamport.azurewebsites.net/pubs/time-clocks.pdf',
    tier: 1,
    kind: 'paper',
    year: 1978,
    authoritativeFor: ['happens-before', 'logical clocks', 'causality without physical time'],
  },
  {
    id: 'gilbert-lynch',
    title: "Brewer's Conjecture and the Feasibility of Consistent, Available, Partition-Tolerant Web Services",
    author: 'Gilbert, Lynch',
    tier: 1,
    kind: 'paper',
    year: 2002,
    authoritativeFor: ['formal CAP statement', 'what CAP actually proves'],
  },
  {
    id: 'abadi-pacelc',
    title: 'Consistency Tradeoffs in Modern Distributed Database System Design (PACELC)',
    author: 'Daniel Abadi',
    tier: 1,
    kind: 'paper',
    year: 2012,
    authoritativeFor: ['latency vs consistency in the absence of partitions', 'PACELC'],
  },
  {
    id: 'tail-at-scale',
    title: 'The Tail at Scale',
    author: 'Dean, Barroso',
    url: 'https://research.google/pubs/pub40801/',
    tier: 1,
    kind: 'paper',
    year: 2013,
    authoritativeFor: [
      'latency amplification with fanout',
      'hedged requests',
      'tail-tolerant techniques',
    ],
  },
  {
    id: 'dapper',
    title: 'Dapper, a Large-Scale Distributed Systems Tracing Infrastructure',
    author: 'Sigelman et al.',
    url: 'https://research.google/pubs/pub36356/',
    tier: 1,
    kind: 'paper',
    year: 2010,
    authoritativeFor: ['distributed tracing', 'spans', 'trace sampling'],
  },
  {
    id: 'kafka-paper',
    title: 'Kafka: a Distributed Messaging System for Log Processing',
    author: 'Kreps, Narkhede, Rao',
    tier: 1,
    kind: 'paper',
    year: 2011,
    authoritativeFor: ['partitioned log', 'consumer offsets', 'throughput-oriented messaging'],
  },
  {
    id: 'cassandra-paper',
    title: 'Cassandra: A Decentralized Structured Storage System',
    author: 'Lakshman, Malik',
    tier: 1,
    kind: 'paper',
    year: 2009,
    authoritativeFor: ['ring partitioning', 'tunable consistency', 'wide-column at scale'],
  },
  {
    id: 'chubby',
    title: 'The Chubby Lock Service for Loosely-Coupled Distributed Systems',
    author: 'Mike Burrows',
    url: 'https://research.google/pubs/pub27897/',
    tier: 1,
    kind: 'paper',
    year: 2006,
    authoritativeFor: ['distributed locks', 'leases', 'coarse-grained coordination'],
  },

  /* ------------------------------------------------------ tier 1: official docs */
  {
    id: 'postgres-docs',
    title: 'PostgreSQL Documentation',
    url: 'https://www.postgresql.org/docs/current/',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: [
      'MVCC',
      'isolation levels as implemented',
      'index types',
      'query planning',
      'WAL',
      'replication',
    ],
  },
  {
    id: 'mysql-docs',
    title: 'MySQL Reference Manual',
    url: 'https://dev.mysql.com/doc/',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: ['InnoDB storage', 'locking', 'binlog replication', 'index behaviour'],
  },
  {
    id: 'redis-docs',
    title: 'Redis Documentation',
    url: 'https://redis.io/docs/latest/',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: [
      'data structures',
      'eviction policies',
      'persistence modes',
      'replication and failover',
      'cluster hash slots',
    ],
  },
  {
    id: 'kafka-docs',
    title: 'Apache Kafka Documentation',
    url: 'https://kafka.apache.org/documentation/',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: [
      'partitions and ordering',
      'consumer groups',
      'delivery semantics',
      'idempotent producer',
      'transactions',
      'retention',
    ],
  },
  {
    id: 'cassandra-docs',
    title: 'Apache Cassandra Documentation',
    url: 'https://cassandra.apache.org/doc/latest/',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: ['tunable consistency levels', 'partition keys', 'compaction strategies'],
  },
  {
    id: 'elasticsearch-docs',
    title: 'Elasticsearch Documentation',
    url: 'https://www.elastic.co/docs',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: ['inverted index', 'analyzers', 'shards and replicas', 'refresh interval'],
  },
  {
    id: 'cockroach-docs',
    title: 'CockroachDB Architecture Documentation',
    url: 'https://www.cockroachlabs.com/docs/stable/architecture/overview',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: ['distributed SQL', 'range-based sharding', 'Raft-backed replication'],
  },
  {
    id: 'clickhouse-docs',
    title: 'ClickHouse Documentation',
    url: 'https://clickhouse.com/docs',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: ['columnar storage', 'OLAP query execution', 'materialized views'],
  },
  {
    id: 'mdn-http',
    title: 'MDN Web Docs: HTTP',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP',
    tier: 1,
    kind: 'official-docs',
    authoritativeFor: ['browser HTTP behaviour', 'caching headers in practice', 'cookies', 'CORS'],
  },

  /* ------------------------------------------------------ tier 2: books and courses */
  {
    id: 'ddia',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    url: 'https://dataintensive.net/',
    tier: 2,
    kind: 'book',
    year: 2017,
    authoritativeFor: [
      'replication models',
      'partitioning',
      'transaction isolation anomalies',
      'consistency models',
      'stream processing',
      'trade-off framing',
    ],
  },
  {
    id: 'database-internals',
    title: 'Database Internals',
    author: 'Alex Petrov',
    tier: 2,
    kind: 'book',
    year: 2019,
    authoritativeFor: ['B-trees', 'LSM trees', 'storage engine internals', 'distributed consensus'],
  },
  {
    id: 'sre-book',
    title: 'Site Reliability Engineering',
    author: 'Google SRE',
    url: 'https://sre.google/sre-book/table-of-contents/',
    tier: 2,
    kind: 'book',
    year: 2016,
    authoritativeFor: [
      'SLI/SLO/SLA',
      'error budgets',
      'the four golden signals',
      'cascading failure mechanics',
      'incident response',
    ],
  },
  {
    id: 'sre-workbook',
    title: 'The Site Reliability Workbook',
    author: 'Google SRE',
    url: 'https://sre.google/workbook/table-of-contents/',
    tier: 2,
    kind: 'book',
    year: 2018,
    authoritativeFor: ['implementing SLOs', 'alerting on burn rate', 'practical reliability work'],
  },
  {
    id: 'release-it',
    title: 'Release It! Design and Deploy Production-Ready Software',
    author: 'Michael T. Nygard',
    tier: 2,
    kind: 'book',
    year: 2018,
    authoritativeFor: [
      'stability patterns',
      'circuit breaker',
      'bulkhead',
      'failure propagation in production',
    ],
  },
  {
    id: 'building-microservices',
    title: 'Building Microservices',
    author: 'Sam Newman',
    tier: 2,
    kind: 'book',
    year: 2021,
    authoritativeFor: ['service decomposition', 'organisational boundaries', 'migration strategies'],
  },
  {
    id: 'hpbn',
    title: 'High Performance Browser Networking',
    author: 'Ilya Grigorik',
    url: 'https://hpbn.co/',
    tier: 2,
    kind: 'book',
    year: 2013,
    authoritativeFor: ['latency budgets', 'TCP behaviour for web traffic', 'connection management'],
  },
  {
    id: 'ostep',
    title: 'Operating Systems: Three Easy Pieces',
    author: 'Arpaci-Dusseau',
    url: 'https://pages.cs.wisc.edu/~remzi/OSTEP/',
    tier: 2,
    kind: 'book',
    authoritativeFor: ['processes and threads', 'concurrency primitives', 'virtual memory', 'I/O'],
  },
  {
    id: 'mit-6584',
    title: 'MIT 6.5840: Distributed Systems',
    url: 'https://pdos.csail.mit.edu/6.5840/',
    tier: 2,
    kind: 'course',
    authoritativeFor: ['fault tolerance', 'replication', 'consensus implementation', 'linearizability'],
  },
  {
    id: 'fundamentals-arch',
    title: 'Fundamentals of Software Architecture',
    author: 'Mark Richards, Neal Ford',
    tier: 2,
    kind: 'book',
    year: 2020,
    authoritativeFor: ['architecture characteristics', 'architectural styles', 'trade-off analysis'],
  },
  {
    id: 'van-steen',
    title: 'Distributed Systems',
    author: 'van Steen, Tanenbaum',
    tier: 2,
    kind: 'book',
    authoritativeFor: ['distributed algorithms', 'coordination', 'naming', 'fault models'],
  },

  /* ------------------------------------------------------ tier 2/3: frameworks */
  {
    id: 'aws-well-architected',
    title: 'AWS Well-Architected Framework',
    url: 'https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html',
    tier: 2,
    kind: 'official-docs',
    authoritativeFor: [
      'architecture review pillars',
      'reliability practices',
      'cost optimisation framing',
    ],
  },
  {
    id: 'azure-arch',
    title: 'Azure Architecture Center',
    url: 'https://learn.microsoft.com/azure/architecture/',
    tier: 2,
    kind: 'official-docs',
    authoritativeFor: ['cloud design patterns', 'reliability patterns', 'integration patterns'],
  },
  {
    id: 'gcp-arch',
    title: 'Google Cloud Architecture Center',
    url: 'https://cloud.google.com/architecture',
    tier: 2,
    kind: 'official-docs',
    authoritativeFor: ['reference architectures', 'reliability guidance', 'data architectures'],
  },

  /* ------------------------------------------------------ tier 3: engineering blogs */
  {
    id: 'aws-builders-library',
    title: "Amazon Builders' Library",
    url: 'https://aws.amazon.com/builders-library/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: [
      'timeouts and retries in practice',
      'load shedding',
      'avoiding fallback',
      'operational lessons at scale',
    ],
  },
  {
    id: 'aws-jitter',
    title: 'Exponential Backoff And Jitter',
    author: 'Marc Brooker (AWS Architecture Blog)',
    url: 'https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/',
    tier: 3,
    kind: 'engineering-blog',
    year: 2015,
    authoritativeFor: ['why jitter matters', 'retry storm behaviour', 'full vs decorrelated jitter'],
  },
  {
    id: 'aws-timeouts',
    title: 'Timeouts, retries, and backoff with jitter',
    author: "Marc Brooker (Amazon Builders' Library)",
    url: 'https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['retry budgets', 'timeout selection', 'backoff strategies'],
  },
  {
    id: 'aws-load-shedding',
    title: 'Using load shedding to avoid overload',
    author: "David Yanacek (Amazon Builders' Library)",
    url: 'https://aws.amazon.com/builders-library/using-load-shedding-to-avoid-overload/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['admission control', 'goodput vs throughput', 'queue depth as a signal'],
  },
  {
    id: 'netflix-tech',
    title: 'Netflix Technology Blog',
    url: 'https://netflixtechblog.com/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['resilience engineering', 'streaming delivery', 'chaos testing practice'],
  },
  {
    id: 'uber-eng',
    title: 'Uber Engineering Blog',
    url: 'https://www.uber.com/blog/engineering/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['geospatial indexing', 'real-time marketplaces', 'large-scale data platforms'],
  },
  {
    id: 'meta-eng',
    title: 'Meta Engineering Blog',
    url: 'https://engineering.fb.com/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['social graph storage', 'feed delivery', 'large-scale caching'],
  },
  {
    id: 'cloudflare-blog',
    title: 'Cloudflare Blog',
    url: 'https://blog.cloudflare.com/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['edge networking', 'anycast', 'DDoS mitigation', 'DNS at scale'],
  },
  {
    id: 'stripe-eng',
    title: 'Stripe Engineering Blog',
    url: 'https://stripe.com/blog/engineering',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['idempotency keys in payment APIs', 'API versioning', 'webhook delivery'],
  },
  {
    id: 'discord-eng',
    title: 'Discord Engineering Blog',
    url: 'https://discord.com/blog/category/engineering',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['real-time messaging at scale', 'stateful connection handling'],
  },
  {
    id: 'dropbox-tech',
    title: 'Dropbox Tech Blog',
    url: 'https://dropbox.tech/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['file synchronisation', 'large-scale storage migration'],
  },
  {
    id: 'linkedin-eng',
    title: 'LinkedIn Engineering Blog',
    url: 'https://engineering.linkedin.com/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['log-centric data infrastructure', 'search and feed systems'],
  },
  {
    id: 'datadog-eng',
    title: 'Datadog Engineering Blog',
    url: 'https://www.datadoghq.com/blog/engineering/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['high-volume telemetry ingest', 'metrics storage', 'observability practice'],
  },
  {
    id: 'martin-fowler',
    title: 'martinfowler.com',
    author: 'Martin Fowler',
    url: 'https://martinfowler.com/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: [
      'architectural terminology',
      'CQRS and event sourcing definitions',
      'strangler fig migration',
      'microservice trade-offs',
    ],
  },
  {
    id: 'brendan-gregg',
    title: 'Brendan Gregg: Systems Performance',
    url: 'https://www.brendangregg.com/',
    tier: 3,
    kind: 'engineering-blog',
    authoritativeFor: ['USE method', 'performance analysis methodology', 'latency profiling'],
  },

  /* ------------------------------------------------------ tier 4: interview convention */
  {
    id: 'hello-interview',
    title: 'Hello Interview',
    url: 'https://www.hellointerview.com/',
    tier: 4,
    kind: 'interview-prep',
    authoritativeFor: ['interview structure', 'communication expectations', 'scoring rubrics'],
  },
  {
    id: 'system-design-primer',
    title: 'The System Design Primer',
    author: 'Donne Martin',
    url: 'https://github.com/donnemartin/system-design-primer',
    tier: 4,
    kind: 'interview-prep',
    authoritativeFor: ['common interview topic coverage', 'question inventory'],
  },
  {
    id: 'exponent',
    title: 'Exponent',
    url: 'https://www.tryexponent.com/',
    tier: 4,
    kind: 'interview-prep',
    authoritativeFor: ['mock interview format', 'interview communication coaching'],
  },
];

export const SOURCE_BY_ID: Record<string, Source> = Object.fromEntries(
  SOURCES.map((s) => [s.id, s]),
);

export function getSource(id: string): Source | undefined {
  return SOURCE_BY_ID[id];
}
