import type { Symptom } from '@/lib/types';

/**
 * Symptom index: the bridge between how a problem *feels* and the concepts that explain it.
 *
 * This is what makes search conceptual rather than lexical (brief section 33). A learner
 * types what they observed; the search expands it into the concepts that actually matter,
 * then ranks lessons, patterns and failures by those concepts.
 *
 * Every entry must earn its place: if the phrase does not appear in a real incident channel
 * or a real interview, it does not belong here.
 */
export const SYMPTOMS: Symptom[] = [
  {
    phrase: 'database gets slow',
    aliases: [
      'db slow',
      'queries are slow',
      'database is the bottleneck',
      'slow sql',
      'database cpu high',
    ],
    concepts: [
      'index',
      'query-plan',
      'n-plus-one',
      'connection-pooling',
      'page-cache',
      'replication-for-reads',
      'sharding',
      'cache-generic',
      'hot-partition',
      'olap',
    ],
    why: 'Almost always one of: a missing index, a plan that changed, too many round trips, a working set that stopped fitting in memory, or analytical queries on a transactional database.',
  },
  {
    phrase: 'duplicate payment',
    aliases: [
      'charged twice',
      'double charge',
      'duplicate order',
      'processed twice',
      'double submit',
    ],
    concepts: [
      'idempotency',
      'idempotency-key',
      'at-least-once',
      'retry',
      'duplicate-processing',
      'exactly-once',
      'atomicity',
      'outbox',
    ],
    why: 'A retry crossed a non-idempotent effect. The fix is never "stop retrying"; it is to make the effect safe to repeat and to record the outcome under a caller-supplied key.',
  },
  {
    phrase: 'everything went down at once',
    aliases: [
      'total outage',
      'whole site down',
      'all services failing',
      'full outage',
      'everything is 500',
    ],
    concepts: [
      'cascading-failure',
      'retry-amplification',
      'health-check',
      'timeout',
      'connection-exhaustion',
      'circuit-breaker',
      'load-shedding',
      'blast-radius',
    ],
    why: 'Simultaneous total failure is usually a shared dependency, a deep health check marking every instance unhealthy at once, or retries multiplying load onto something already struggling.',
  },
  {
    phrase: 'it is fast for most users but terrible for some',
    aliases: [
      'p99 is bad',
      'some requests are slow',
      'slow tail',
      'intermittent slowness',
      'random timeouts',
    ],
    concepts: [
      'tail-latency',
      'percentiles',
      'fanout-latency-amplification',
      'hot-key',
      'compaction',
      'hedged-request',
      'noisy-neighbour',
      'coordinated-omission',
    ],
    why: 'The average is fine and the tail is not. Look for fanout, garbage collection, compaction, a hot partition, or one tenant consuming shared capacity.',
  },
  {
    phrase: 'user does not see their own update',
    aliases: [
      'stale data after write',
      'my change disappeared',
      'refresh shows old value',
      'update not visible',
    ],
    concepts: [
      'replication-lag',
      'read-your-writes',
      'eventual-consistency',
      'cache-invalidation',
      'session-guarantees',
      'sticky-sessions',
    ],
    why: 'The write went to a leader and the read went to a replica, or to a cache. This is a session-guarantee problem, not a bug in the database.',
  },
  {
    phrase: 'the cache went down and took everything with it',
    aliases: [
      'cache outage',
      'redis down',
      'cold cache',
      'cache restart caused outage',
      'origin overloaded after deploy',
    ],
    concepts: [
      'cache-stampede',
      'request-coalescing',
      'thundering-herd',
      'capacity-headroom',
      'load-shedding',
      'graceful-degradation',
      'hit-rate',
    ],
    why: 'The origin was sized for the cache miss rate, not the request rate. When the cache empties, the database receives traffic it has never been able to serve.',
  },
  {
    phrase: 'one customer is slowing everyone down',
    aliases: [
      'noisy neighbour',
      'one tenant hogging',
      'a single user broke it',
      'abusive client',
    ],
    concepts: [
      'noisy-neighbour',
      'rate-limiting',
      'bulkhead',
      'admission-control',
      'tenant-isolation',
      'cell-architecture',
      'token-bucket',
    ],
    why: 'Shared capacity with no per-tenant limit. The answer is isolation plus a quota, applied before the expensive work starts.',
  },
  {
    phrase: 'the queue keeps growing',
    aliases: ['consumer lag', 'backlog', 'messages piling up', 'lag increasing', 'falling behind'],
    concepts: [
      'queue-depth',
      'backpressure',
      'consumer-group',
      'partition-ordering',
      'poison-message',
      'load-shedding',
      'littles-law',
    ],
    why: 'Arrival rate exceeds service rate. Either the consumers are too few, parallelism is capped by partition count, or one poison message is blocking a partition.',
  },
  {
    phrase: 'two servers both think they are the leader',
    aliases: ['split brain', 'double leader', 'both primaries accepting writes', 'divergent data'],
    concepts: [
      'split-brain',
      'leader-election',
      'quorum',
      'fencing-token',
      'lease',
      'network-partition',
      'failure-detector',
    ],
    why: 'A failure detector cannot distinguish a dead node from an unreachable one. Only quorum plus fencing makes the old leader harmless.',
  },
  {
    phrase: 'we cannot deploy without downtime',
    aliases: [
      'migration needs maintenance window',
      'deploy breaks clients',
      'rollback impossible',
      'schema change is scary',
    ],
    concepts: [
      'schema-migration',
      'expand-contract',
      'backward-compatibility',
      'rollback',
      'canary',
      'feature-flag',
      'backfill',
    ],
    why: 'During any rollout, two versions of the code run against one dataset. Every change has to be compatible in both directions for the length of the rollout.',
  },
  {
    phrase: 'the counter is wrong',
    aliases: ['lost updates', 'count drifts', 'race condition on write', 'concurrent writes clobber'],
    concepts: [
      'lost-update',
      'optimistic-concurrency',
      'locking',
      'isolation-levels',
      'last-write-wins',
      'crdt',
    ],
    why: 'Two read-modify-write cycles overlapped. Either serialise them, use a conditional write, or use a data type whose merge is defined.',
  },
  {
    phrase: 'it works in one region and not the other',
    aliases: [
      'cross region issues',
      'replication between regions',
      'multi region consistency',
      'failover to other region failed',
    ],
    concepts: [
      'multi-region',
      'active-active',
      'active-passive',
      'replication-lag',
      'conflict-resolution',
      'rtt',
      'data-residency',
    ],
    why: 'Cross-region latency makes synchronous coordination expensive, so most designs go asynchronous and inherit conflicts and staleness.',
  },
  {
    phrase: 'we ran out of connections',
    aliases: [
      'too many connections',
      'connection pool exhausted',
      'file descriptor limit',
      'requests hang',
    ],
    concepts: [
      'connection-exhaustion',
      'connection-pooling',
      'littles-law',
      'timeout',
      'backpressure',
      'bulkhead',
    ],
    why: 'Concurrency equals arrival rate times service time. When service time rises, required connections rise with it, and the pool becomes the queue.',
  },
  {
    phrase: 'traffic spiked and autoscaling did not help',
    aliases: ['sudden spike', 'flash crowd', 'launch traffic', 'scaling too slow'],
    concepts: [
      'autoscaling',
      'capacity-headroom',
      'elasticity',
      'load-shedding',
      'thundering-herd',
      'cache-generic',
      'queue',
    ],
    why: 'Scaling takes minutes and spikes take seconds. Spikes are absorbed by headroom, caching, queueing and shedding, not by adding capacity in real time.',
  },
  {
    phrase: 'the search index is out of date',
    aliases: ['stale search results', 'new items not searchable', 'index lag'],
    concepts: [
      'inverted-index',
      'eventual-consistency',
      'cdc',
      'replication-lag',
      'staleness',
      'bounded-staleness',
    ],
    why: 'Search indexes are derived data, updated asynchronously. The design question is what staleness is acceptable, and how you detect when it exceeds that.',
  },
  {
    phrase: 'one popular item is destroying the cluster',
    aliases: ['celebrity problem', 'viral post', 'hot key', 'single key overload', 'flash sale'],
    concepts: [
      'hot-key',
      'hot-partition',
      'key-splitting',
      'local-cache',
      'replication-for-reads',
      'load-distribution',
    ],
    why: 'A single key cannot be partitioned by definition. The options are to replicate it, cache it close to the reader, or split it and pay on read.',
  },
  {
    phrase: 'events arrived out of order',
    aliases: ['ordering problem', 'out of order messages', 'stale event overwrote new one'],
    concepts: [
      'partition-ordering',
      'logical-clock',
      'vector-clock',
      'happens-before',
      'clock-skew',
      'last-write-wins',
      'watermark',
    ],
    why: 'Ordering only holds within a partition. Across partitions or producers you need a causal marker, not a wall-clock timestamp.',
  },
  {
    phrase: 'we lost data',
    aliases: ['data loss', 'missing rows', 'writes disappeared after failover', 'corruption'],
    concepts: [
      'durability',
      'sync-vs-async-replication',
      'rpo',
      'failover',
      'backup',
      'fsync',
      'last-write-wins',
    ],
    why: 'Either the write was acknowledged before it was durable, an asynchronous replica was promoted with a gap, or a conflict resolution rule silently discarded it.',
  },
  {
    phrase: 'the system is too expensive',
    aliases: ['cloud bill', 'cost too high', 'infrastructure spend', 'egress cost'],
    concepts: [
      'cost-optimisation',
      'capacity-planning',
      'cardinality',
      'retention',
      'downsampling',
      'multi-region',
      'sampling',
    ],
    why: 'Cost is usually concentrated in a few places: idle headroom, data egress, observability cardinality, and retention nobody chose deliberately.',
  },
  {
    phrase: 'nobody knows why it broke',
    aliases: ['cannot debug', 'no visibility', 'hard to diagnose', 'where did the time go'],
    concepts: [
      'observability',
      'traces',
      'correlation-id',
      'structured-logging',
      'golden-signals',
      'sampling',
    ],
    why: 'Without a correlation id and traces, a request across services is unreconstructable. Metrics tell you something is wrong; traces tell you where.',
  },
  {
    phrase: 'alerts fire constantly and nobody reacts',
    aliases: ['alert fatigue', 'too many alerts', 'noisy paging', 'on call is miserable'],
    concepts: ['alerting', 'slo', 'error-budget', 'golden-signals', 'incident-response'],
    why: 'Alerting on causes instead of symptoms produces noise. Alert on user-visible symptoms and on how fast the error budget is burning.',
  },
  {
    phrase: 'how many servers do I need',
    aliases: ['capacity estimate', 'sizing', 'how much traffic can it handle', 'rps per server'],
    concepts: [
      'back-of-envelope',
      'littles-law',
      'throughput',
      'capacity-headroom',
      'capacity-planning',
      'bottleneck',
    ],
    why: 'Measure per-unit cost, apply Little’s law for concurrency, then add headroom for the spike you have not seen yet.',
  },
  {
    phrase: 'should I use microservices',
    aliases: ['monolith or microservices', 'split the service', 'service boundaries'],
    concepts: [
      'microservices',
      'modular-monolith',
      'service-boundary',
      'coupling',
      'operational-burden',
      'distributed-transaction',
    ],
    why: 'The question is never "which is better". It is whether independent deployment is worth network calls, partial failure, and losing transactions across the boundary.',
  },
  {
    phrase: 'should I use kafka',
    aliases: ['do I need a queue', 'kafka or sqs', 'message broker choice', 'need a stream'],
    concepts: [
      'queue',
      'log-based-messaging',
      'pubsub',
      'replay',
      'retention',
      'operational-burden',
      'outbox',
    ],
    why: 'A durable replayable log is worth it when multiple independent consumers need history. If one consumer processes each message once and forgets it, a queue is simpler and cheaper.',
  },
  {
    phrase: 'sql or nosql',
    aliases: ['which database', 'relational or document', 'do I need nosql to scale'],
    concepts: [
      'acid',
      'sharding',
      'partition-key',
      'index',
      'denormalisation',
      'isolation-levels',
      'vertical-scaling',
    ],
    why: 'Scale is rarely the deciding factor at realistic sizes. The deciding factors are access patterns, the transactions you need, and how much schema flexibility costs you later.',
  },
  {
    phrase: 'requests time out but the server looks fine',
    aliases: ['server healthy but slow', 'cpu low but slow', 'hanging requests'],
    concepts: [
      'connection-exhaustion',
      'queue-depth',
      'littles-law',
      'timeout',
      'throughput-vs-goodput',
      'head-of-line-blocking',
    ],
    why: 'The bottleneck is not CPU. It is a queue somewhere: a pool, a thread limit, a lock, or a downstream dependency holding your workers hostage.',
  },
  {
    phrase: 'how do I stop abuse',
    aliases: ['scraping', 'bot traffic', 'someone is hammering the api', 'ddos'],
    concepts: [
      'rate-limiting',
      'token-bucket',
      'ddos',
      'admission-control',
      'authn',
      'anycast',
      'tenant-isolation',
    ],
    why: 'Abuse is a capacity problem with an adversary attached. Limit per identity, reject as early and as cheaply as possible, and never let the origin be the filter.',
  },
  {
    phrase: 'the deploy broke production',
    aliases: ['bad release', 'need to roll back', 'regression in production', 'incident after deploy'],
    concepts: ['canary', 'rollback', 'feature-flag', 'blast-radius', 'backward-compatibility', 'ci-cd'],
    why: 'Most outages are self-inflicted by change. The defence is a small blast radius, a fast rollback, and a kill switch that does not require a deploy.',
  },
  {
    phrase: 'deleted data came back',
    aliases: [
      'deleted record reappeared',
      'row came back after deletion',
      'resurrected data',
      'delete did not stick',
      'zombie rows',
    ],
    concepts: [
      'anti-entropy',
      'read-repair',
      'hinted-handoff',
      'leaderless',
      'eventual-consistency',
      'compaction',
      'conflict-resolution',
      'audit-log',
    ],
    why: 'In a replicated store a deletion is a marker that expires. A replica offline longer than that expiry still holds the original row, and reconciliation propagates values rather than absences, so the row wins.',
  },
  {
    phrase: 'some customers stopped getting updates',
    aliases: [
      'one partition is behind',
      'consumer lag on one partition',
      'a few users are stale',
      'processing stopped for some accounts',
      'partition stuck',
    ],
    concepts: [
      'partition-ordering',
      'head-of-line-blocking',
      'poison-message',
      'dead-letter-queue',
      'consumer-group',
      'offset',
      'hot-partition',
      'alerting',
    ],
    why: 'A log has one position per partition, so a message that always fails blocks everything behind it — and aggregate lag hides it completely, because 63 healthy partitions average away the one that is stopped.',
  },
  {
    phrase: 'dashboards got slow and nothing changed',
    aliases: [
      'metrics are slow',
      'too many series',
      'cardinality',
      'monitoring is degraded',
      'alerts firing late',
    ],
    concepts: [
      'cardinality',
      'time-series-storage',
      'index',
      'observability',
      'alerting',
      'tenant-isolation',
      'downsampling',
      'rate-limiting',
    ],
    why: 'Series count is the product of distinct label values, so one unbounded label multiplies it. Sample volume barely moves, which is why every capacity dashboard stays green while the index stops fitting in memory.',
  },
  {
    phrase: 'everyone reconnected at once',
    aliases: [
      'reconnect storm',
      'connection storm',
      'websocket clients all dropped',
      'gateway ran out of file descriptors',
      'brief blip became a long outage',
    ],
    concepts: [
      'websocket',
      'thundering-herd',
      'connection-exhaustion',
      'exponential-backoff',
      'admission-control',
      'load-shedding',
      'cascading-failure',
      'cell-architecture',
    ],
    why: 'Establishing a connection costs orders of magnitude more than using one, and a correlated disconnect asks the tier to do the expensive thing for everybody at once — then displaced clients saturate the gateways that were healthy.',
  },
];

export function findSymptoms(query: string): Symptom[] {
  const q = query.toLowerCase().trim();
  if (q.length < 3) return [];
  return SYMPTOMS.filter(
    (s) =>
      s.phrase.includes(q) ||
      q.includes(s.phrase) ||
      s.aliases.some((a) => a.includes(q) || q.includes(a)),
  );
}
